### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by ValentinJesse** [sameerkumar18/Taurauto-Sharer#1]
Hi!

I've tried for countless of hours to run this script under various circumstances, but i keep encountering errors. Chromedriver keeps crashing with "chromedriver.exe has stopped working" and "data:," written in the address bar instead of the link, and a "Disable developer mode extensions" pops out shortly after.  

![cmd_2017-03-17_21-02-25](https://cloud.githubusercontent.com/assets/7979136/24069996/8ade8cfc-0bb4-11e7-9cb6-11e2b4dfa297.jpg)

I tried to run the script with multiple arguments, from post_script(url) and self.url to pasting just the url, but without succcess. 

Once out of 10-20 runs, the chromedriver does not crash, but neither does it work, Just opens the instance with "data:," in the address bar and gives a "pepper-module" error in cmd. Maybe i'm passing the wrong arguments. 

![chrome_2017-03-18_08-52-28](https://cloud.githubusercontent.com/assets/7979136/24070166/4bf0b778-0bb8-11e7-949e-1bb573e973c2.png)

Need guidance. Thanks!

**Comment by sameerkumar18** [comment]
Hey
Just a few checks before I suggest any thing...
1) You have downloaded the chromedriver.exe
2) You've given the path to it (probably because on Windows you need to)
3) You've changed the group urls in the code.
Are all these points checked at your end?
[Also I forgot to update the readme, wrote few lines in it just now. ]

**Comment by ValentinJesse** [comment]
1 - Yes. I have downloaded the chromedriver with pip install right into the Scripts folder of Python27. 
2 - I've added the Path variable as well for the "Scripts" folder in my Win10 machine
3 - 

![sublime_text_2017-03-18_09-51-00](https://cloud.githubusercontent.com/assets/7979136/24070578/a447f758-0bc0-11e7-803e-48cf643b97bb.jpg)

From what i see, the chromedriver crashes only when it launches with the "Type the caption here:" input. Also, the chrome instance fires up right after i input the caption and press enter.

Additionally, if i run "run.py" without any argument, it gives me "ValueError, need more than 1 value to unpack'

Thanks for the prompt answer.

**Comment by sameerkumar18** [comment]
Probably I found a solution,
Just comment out "self.driver.maximize_window()".
And probably should work this time.

**Comment by ValentinJesse** [comment]
I can confirm that the chromedriver.exe error is not popping out anymore after commenting "self.driver.maximize_window()".

However, the chrome instance just fires up with "data:," in the address bar instead of the facebook link.

**Comment by sameerkumar18** [comment]
And I just saw a mistake that probably you're doing
Except for the comment out thing and adding groups to the list, email id and password need to included in run.py.

**Comment by ValentinJesse** [comment]
Fixed that one earlier. Spotted the mistake. The problem persists, though. Thank you!

What is the correct way of firing up the script ? How do i specify the url of the post that i'm trying to share ?

**Comment by ValentinJesse** [comment]
`from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import time

class AutoShare:

    def __init__(self):
        self.url = 'https://www.facebook.com'
        chrome_options = webdriver.ChromeOptions()
        prefs = {"profile.default_content_setting_values.notifications": 2}
        chrome_options.add_experimental_option("prefs", prefs)
        self.driver = webdriver.Chrome(chrome_options=chrome_options)
       # self.driver.maximize_window()
        self.driver.get(self.url)

    def auth(self,uname,passd):
        time.sleep(2)
        username = self.driver.find_element_by_id('email')
        password = self.driver.find_element_by_id('pass')
        username.send_keys(uname)
        password.send_keys(passd)
        password.send_keys(Keys.ENTER)

    def process(self,post_url, caption_text):
        groups = []
        groups = ['https://www.facebook.com/groups/509773865864286/']
        #          'https://www.facebook.com/groups/delhistartupnetwork/',
        #          'https://www.facebook.com/groups/indianstartupnetwork']
        time.sleep(1)
        if not groups:
            try:
                number_of_groups = int(raw_input("How many groups:"))
                for j in range(0, number_of_groups):
                    app = raw_input("Enter group url(with https)" + str(j + 1) + ":")
                    groups.append(app)
                pass
            except:
                print "Error"

        else:
            pass

        for i in groups:
            try:
                self.driver.get(str(i))
                actions = ActionChains(self.driver)
                time.sleep(2)
                actions.send_keys('p').perform()
                time.sleep(1)

                actions2 = ActionChains(self.driver)
                actions2.send_keys(str(post_url) + " ").perform()
                time.sleep(3)


                actions4 = ActionChains(self.driver)

                for j in range(0, 15):
                    actions4.send_keys(Keys.BACK_SPACE).perform()

                caption = ActionChains(self.driver)
                caption.send_keys(caption_text).perform()

                click_post = self.driver.find_element_by_class_name("_332r")
                click_post.click()
                time.sleep(10)
                print "Successfully posted in " + str(i.split('https://www.facebook.com/groups/')[1].split('/')[0])
            except:
                print"Error posting in " + str(i.split('https://www.facebook.com/groups/')[1].split('/')[0])
        self.driver.close()`

**Comment by sameerkumar18** [comment]
python run.py https://www.facebook.com/events/1728846570763285/

The https://.../. is the url of the post that is to be shared and needs to be changed according to your needs.

**Comment by sameerkumar18** [comment]
Let me know if that runs
Also, I just ran the program on my mac and its working fine to me.

**Comment by ValentinJesse** [comment]
Ok, so my "run.py" looks like:

```
from sys import argv
from AutoShareFacebook import AutoShare

script, post_url = argv
#can access variable post_url
caption_text = raw_input("Type the caption here: ")

auto = AutoShare()

auto.auth(uname='xxxx@gmail.com', passd='mypassword')
auto.process(post_url=post_url, caption_text=caption_text)
```

My AutoShareFacebook.py looks like:

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import time

    class AutoShare:

    def __init__(self):
        self.url = 'https://www.facebook.com'
        chrome_options = webdriver.ChromeOptions()
        prefs = {"profile.default_content_setting_values.notifications": 2}
        chrome_options.add_experimental_option("prefs", prefs)
        self.driver = webdriver.Chrome(chrome_options=chrome_options)
       # self.driver.maximize_window()
        self.driver.get(self.url)

    def auth(self,uname,passd):
        time.sleep(2)
        username = self.driver.find_element_by_id('email')
        password = self.driver.find_element_by_id('pass')
        username.send_keys(uname)
        password.send_keys(passd)
        password.send_keys(Keys.ENTER)

    def process(self,post_url, caption_text):
        groups = []
        groups = ['https://www.facebook.com/groups/509773865864286/']
        #          'https://www.facebook.com/groups/delhistartupnetwork/',
        #          'https://www.facebook.com/groups/indianstartupnetwork']
        time.sleep(1)
        if not groups:
            try:
                number_of_groups = int(raw_input("How many groups:"))
                for j in range(0, number_of_groups):
                    app = raw_input("Enter group url(with https)" + str(j + 1) + ":")
                    groups.append(app)
                pass
            except:
                print "Error"

        else:
            pass

        for i in groups:
            try:
                self.driver.get(str(i))
                actions = ActionChains(self.driver)
                time.sleep(2)
                actions.send_keys('p').perform()
                time.sleep(1)

                actions2 = ActionChains(self.driver)
                actions2.send_keys(str(post_url) + " ").perform()
                time.sleep(3)


                actions4 = ActionChains(self.driver)

                for j in range(0, 15):
                    actions4.send_keys(Keys.BACK_SPACE).perform()

                caption = ActionChains(self.driver)
                caption.send_keys(caption_text).perform()

                click_post = self.driver.find_element_by_class_name("_332r")
                click_post.click()
                time.sleep(10)
                print "Successfully posted in " + str(i.split('https://www.facebook.com/groups/')[1].split('/')[0])
            except:
                print"Error posting in " + str(i.split('https://www.facebook.com/groups/')[1].split('/')[0])
        self.driver.close()

```
When i launch the script with "python run.py https://www.facebook.com/aspeagro/posts/1247537575299992", it tells me to input a caption and then fires up the chrome instance.

The chrome instance opens up with this: (and with"data:," in the address bar)

![cmd_2017-03-18_11-27-37](https://cloud.githubusercontent.com/assets/7979136/24071266/4442bd4e-0bce-11e7-8c7a-7540728e1220.png)

And then i receive this in the command prompt:

> C:\Users\Valentin\Desktop\automate\social\facebook\auto-share-facebook-groups>run.py https://www.facebook.com/aspeagro/posts/1247537575299992
Type the caption here: test
Traceback (most recent call last):
  File "C:\Users\Valentin\Desktop\automate\social\facebook\auto-share-facebook-groups\run.py", line 8, in <module>
    auto = AutoShare()
  File "C:\Users\Valentin\Desktop\automate\social\facebook\auto-share-facebook-groups\AutoShareFacebook.py", line 35, in __init__
    self.driver.get(self.url)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 250, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"11448.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=57.0.2987.110)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)

**Comment by ValentinJesse** [comment]
Additionally, what's interesting is that the script is taking the "chromedriver.exe" that's in the same folder as the script instead of the one from the Python27/Scripts folder, even though i've set up the Environment variables in my Win10 machine. 

If i delete the chromedriver.exe from the "auto-share-facebook-groups" folder, then the script crashes and doesn't show the chrome window.

**Comment by sameerkumar18** [comment]
Try replacing the current "self.driver = webdriver.Chrome(chrome_options=chrome_options)"

With this "self.driver = webdriver.Chrome(chrome_options=chrome_options,executable_path='__path__')"
where __path__ is the path to chromedriver.exe 

For example:  
self.driver = webdriver.Chrome(chrome_options=chrome_options,executable_path='C:....chromedriver.exe')

**Comment by ValentinJesse** [comment]
Thanks for all the help.

Unfortunately:

1
![sublime_text_2017-03-18_12-57-25](https://cloud.githubusercontent.com/assets/7979136/24071760/863b26b2-0bda-11e7-9442-356a09d436bb.png)

2
![cmd_2017-03-18_12-56-36](https://cloud.githubusercontent.com/assets/7979136/24071765/92bf8860-0bda-11e7-9d25-b9b49589787f.png)


3
![chrome_2017-03-18_12-56-56](https://cloud.githubusercontent.com/assets/7979136/24071763/8e3f65f8-0bda-11e7-9243-7e0af42e3f4c.png)

**Comment by ValentinJesse** [comment]
Updated the chromedriver.exe with the latest version (compatible with chrome 57) and fixed the issue. 

The script works great and it will probably save me a ton of hours per month, given that i have to manage multiple pages and post in at least 30 (soon by the hundreds) groups for each.

Now, in regards to sharing to multiple groups, is there a way to make the script fire up at random intervals [example: "1-3 minutes between sharing to each of the groups listed in the script"] to avoid getting banned by facebook ?

Like this:

```
    def process(self,post_url, caption_text):
        groups = []
        groups = ['https://www.facebook.com/groups/509773865864286/',] - 1:21 minutes
                    'https://www.facebook.com/groups/delhistartupnetwork/', - 2 minutes
                    'https://www.facebook.com/groups/indianstartupnetwork'] - 3 minutes
                    'https://www.facebook.com/groups/aaa'] - 2:20 minutes
        etc
```

Sorry for taking out so much of your time and thanks for the fantastic script.

**Comment by sameerkumar18** [comment]
I've been brainstorming since your last few statement about what one thing could cause such an issue. Phew!
Talking about the random intervals, that actually needs a random values for time.sleep()

You can try on your own or just fork it and ping me and I can probably include that feature for you and push to your forked repo.

**Comment by ValentinJesse** [comment]
Ok, what i did was:

1 - import random
2 - replaced "timesleep(10) [the one at the bottom] with "time.sleep(40.75 + 35.5*random.random())" (will modify accordingly)

Now, i wonder if there's a way to import a txt or rtf file from the same folder as the script instead of writing the caption in CMD. The reason for this is that when i share, i usually post longer comments that include more lines, spacing, links etc. Is there a way to achieve this? Thanks!

**Comment by ValentinJesse** [comment]
I also wonder if there's a way to minimize the chromedriver when it starts. Preferably to not see it at all,
not even when it starts (only in the taskbar)

**Comment by sameerkumar18** [comment]
For fetching the caption from a txt file you could probably refer this http://www.pythonforbeginners.com/files/reading-and-writing-files-in-python

**Comment by sameerkumar18** [comment]
You can try minimizing the Chrome window if that works else you will need a headerless way like PhantomJS

**Comment by ValentinJesse** [comment]
Thanks for everything. I will follow your suggestions
