### ISSUE TITLE
Well, Upload seems to be disabled.

### ISSUE THREAD

**Issue by sohanmanju** [sameerkumar18/Taurauto-Sharer#3]

**Comment by sameerkumar18** [comment]
@codenoob28 Didn't get you!
Upload for?

**Comment by sohanmanju** [comment]
I tried to upload a bot onto the Instagram file. I wasn't able to. It said:
Uploads are disabled.
File uploads require push access to this repository.

**Comment by sameerkumar18** [comment]
Please fork the repo first, make changes to the forked repo and then make a pull request to the original repo :)
